### ISSUE TITLE
ECDSA vs RSA ?

### ISSUE THREAD

**Issue by punkeel** [mozilla/server-side-tls#117]
Hello,

I know this is not really the right place to ask, but why do you prefer RSA over ECDSA ? (ex: `ECDHE-RSA-AES128-GCM-SHA256` is before `ECDHE-ECDSA-AES128-GCM-SHA256`).

Moreover (correct me if I'm wrong), a 256bits ECDSA certificate provides the same security level as a 2048bits RSA one ... so why preferring RSA over ECDSA ?

(I've inverted the two for my personal use, as ECDSA certificates are said to use less CPU.)

Edit: Hmm... Looks like https://wiki.mozilla.org/Security/Server_Side_TLS gives the "correct" order, but not https://mozilla.github.io/server-side-tls/ssl-config-generator/, no matter the OpenSSL version

**Comment by jvehent** [comment]
The ordering of ECDSA versus RSA ciphersuites isn't relevant. If you use a RSA certificate, RSA ciphersuites will be used, and vice versa.

That said, if given the choice, we recommend you use an ECDSA certificate. For now, we recommend P-256, because it is common enough and well supported in libraries. In the future, we may recommend P-384 for the extra security.

Note: I updated the wiki page yesterday but didn't yet get a chance to update the config generator. This will be done soon.

**Comment by punkeel** [comment]
It matters because I'm using two certificates: RSA and ECDSA.

No problem, thanks a lot for your response and for the great work done here :+1:

**Comment by jvehent** [comment]
Ha, then indeed the ordering matters. You'll note that the wiki, which has the latest information, prefers ECDSA.
