### ISSUE TITLE
ssl_session_tickets off breaks Chrome and Firefox.

### ISSUE THREAD

**Issue by vpbxlgb** [mozilla/server-side-tls#134]
In the configuration sample, ssl_session_tickets off breaks lasted Chrome and Firefox releases. Safari works fine.

**Comment by tomato42** [comment]
if this indeed breaks them, then it's a bug in them, not in configuration. Session ticket support is not mandatory part of TLS protocol...

**Comment by vpbxlgb** [comment]
Ok. It broke multiple browser across platforms. We had to remove it to deliver secure services.

**Comment by janbrasna** [comment]
For investigation details (possibly a bug in OpenSSL <1.0.2l) see: https://github.com/certbot/certbot/issues/7322

Fixed in https://github.com/mozilla/ssl-config-generator/commit/db419f0a0a2fd8c618957f11e3a514e244fede85

Can be enabled back for nginx now:
- https://github.com/mozilla/server-side-tls/issues/284
