### ISSUE TITLE
Sweet32 Birthday attacks on 64-bit block ciphers in TLS

### ISSUE THREAD

**Issue by rugk** [mozilla/server-side-tls#156]
See https://sweet32.info/

CVE-2016-2183, CVE-2016-6329

So what do you consider to do? Dropping 3DES from the Intermediate level?

And what to do about the [RC4 issue](https://wiki.mozilla.org/Security/Server_Side_TLS#RC4_weaknesses) now?

> In a public discussion ([bug 927045](https://bugzilla.mozilla.org/show_bug.cgi?id=927045)), it has been recommended to replace RC4 with 3DES. This would impact Internet Explorer 7 and 8 users that, depending on the OS, do not support AES, and will negotiate only RC4 or 3DES ciphers. Internet Explorer uses the cryptographic library “schannel”, which is OS dependent. schannel supports AES in Windows Vista, but not in Windows XP.
> 
> While 3DES provides more resistant cryptography, it is also 30 times slower and more cpu intensive than RC4. For large web infrastructure, the CPU cost of replacing RC4 with 3DES is non-zero. For this reason, we recommend that administrators evaluate their traffic patterns, and make the decision of replacing RC4 with 3DES on a per-case basis. At Mozilla, we evaluated that the impact on CPU usage is minor, and thus decided to replace RC4 with 3DES where backward compatibility is required.

I assume this attack makes the decision between RC4 and 3DES harder.

**Comment by tomato42** [comment]
Exploiting the 3DES issue is harder in practice, as you can't keep connection open indefinitely against Apache or nginx, so 3DES is still better than RC4.

but I guess that means we should move Windows XP and Windows 2003 compatibility completely to legacy level.

**Comment by jvehent** [comment]
I don't think we should rush removing 3DES from the intermediate configuration. That is certainly a long term goal, but [stats from the real world](https://jve.linuxwall.info/blog/index.php?post/2016/08/04/TLS-stats-from-1.6-billion-connections-to-mozilla.org) show that it is still significantly used (2.8%).

I would propose to continue the work that has started on v5 of the guidelines, planned for early 2017, and as @tomato42 proposes, try to move 3DES to the old level then.

**Comment by april** [comment]
Even with modern clients, it's still in use about 1% of the time, which is pretty high:

https://ipv.sx/telemetry/general-v2.html?channels=release&measure=SSL_SYMMETRIC_CIPHER_FULL&target=4&absolute=0&relative=1

**Comment by jvehent** [comment]
> Even with modern clients, it's still in use about 1% of the time, which is pretty high.

That's a concern for browsers and a reason for not disabling 3DES for a little while longer. I think we'll end up repeating the RC4 story here, and go through several months of pain while sites learn to migrate to better ciphersuites, until 3DES can be removed from the browser.

Let's operate under the assumption 3DES will be removed from the intermediate conf in v5 and see where that takes us.

**Comment by robert-scheck** [comment]
I would like to see DES-CBC3 in legacy rather in intermediate level as soon as possible, given that affected operating systems and browsers are EOL for quite some time already, if I'm not completely mistaken.

**Comment by frkay** [comment]
Keep in mind that mozilla.org stats are somewhat biased since some users get there only to download Firefox using the default browser they have at hand on their old Windows systems. The web is quickly becoming less inclined to support IE 7 and 8, many sites are now designed for IE 9 and up and the fact that [Windows XP is not handling SNI](http://caniuse.com/#feat=sni) which is more and more used to provide "HTTPS everywhere" (for instance web hosting companies like [Infomaniak](https://news.infomaniak.com/certificats-ssl-gratuits-chez-infomaniak/) and [OVH](https://www.ovh.com/fr/hebergement-web/ssl_mutualise.xml) offer HTTPS for free using Let's Encrypt certificates and SNI) is a real pain for IE7/8 users.
Perhaps a new compatibility level especially tailored for servers that rely on SNI should be added since in this case IE on Windows XP is definitely out of the game and AES is largely available, to get an idea you can take a peak at what OVH has done for its free HTTPS offer on this [SSL Labs result](https://www.ssllabs.com/ssltest/analyze.html?d=www.esparquet.com) it's clean and pretty remarkable that the sole SNI aware "browser" that is not able to handle ECDHE is OpenSSL 0.9.8y.

**Comment by nbibler** [comment]
Just to follow up on @frkay's comment... very few, if any, sites in active development still officially support IE7 and IE8. IE9 is even largely an afterthought (if it's thought of at all) for current applications, in fact.

Since the introduction of the forced/auto-updates by Microsoft, IE9 ([0.38%](http://caniuse.com/usage-table)) actually has less usage than IE8 ([0.55%](http://caniuse.com/usage-table)) and those users have migrated up the IE chain to IE11 (4.18%) or migrated to Edge (1.42%).

**Comment by bk2204** [comment]
Just as a note, because of the recommendation for 3DES, systems deploying the intermediate configuration now fail PCI compliance scanners.  This is a problem for a variety of people, but especially in shared web hosting.

**Comment by jcoby** [comment]
@bk2204 intermediate not only fails PCI scans but cannot be contested, even given the information from the sweet32 website and Mozilla. Our ASV will not pass any config that includes 3DES. We had to move to modern.

**Comment by bk2204** [comment]
@jcoby Unfortunately, the configurations I'm looking at updating are the default ones for cPanel & WHM. I can't deploy a default configuration that doesn't work on TLS 1.0, especially since there are still many RHEL/CentOS 5 systems out there, no matter how much I would like to.

**Comment by robert-scheck** [comment]
Since end of March, RHEL and CentOS 5 are EOL – while RHEL 5 customers still can get critical security updates if the bought the ELS add-on. Thus running (especially) CentOS 5 these days on a public network is IMHO anyway completely irresponsible.

Aside of this, Qualys SSL Labs reports meanwhile the following ciphers as "weak" in the intermediate compatibility as suggested by Mozilla:

  * TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA (0xc012)   ECDH secp256r1 (eq. 3072 bits RSA)   FS   WEAK 	112
  * TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA (0x16)   DH 4096 bits   FS   WEAK 	112
  * TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)   WEAK 	112

So, can we please get rid of 3DES in intermediate compatibility?

**Comment by tomato42** [comment]
> Since end of March, RHEL and CentOS 5 are EOL – while RHEL 5 customers still can get critical security updates if the bought the ELS add-on. Thus running (especially) CentOS 5 these days on a public network is IMHO anyway completely irresponsible.

This bug is (essentially) about 3DES. Alternative to which are AES ciphers, and AES ciphers are supported since at least RHEL 3 so for RHEL/CentOS, removal of 3DES from Intermediate is not an issue.

if anything, it would be an argument to remove TLS1.0 from intermediate, but is something completely unrelated to sweet32.

**Comment by april** [comment]
3DES has been dropped from Intermediate in 5.0.
