### ISSUE TITLE
Simplify the cipher suite

### ISSUE THREAD

**Issue by solarus0** [mozilla/server-side-tls#168]
Hi,
I think that your cipher suite are way too complicate.
You can get the same result using cipher’s family instead of enumerate each cipher.

For exemple the modern cipher suite can be factorized using this suite ;
ECDHE+CHACHA20:ECDHE+AES:!SHA1

The intermediate suite can be this ;
EECDH+CHACHA20:EECDH+AES:DHE-RSA-AES256-SHA:AES128-SHA
It’s compatible with all common browser exept IE6 and IE8 for XP

And the old suite to support IE6 could be this ;
EECDH+CHACHA20:EECDH+AES:DHE-RSA-AES256-SHA:AES128-SHA:DES-CBC3-SHA

What do you thing about this change ?

**Comment by jvehent** [comment]
You can't control ordering well when using macros. This has been discussed many many times, and we always have the same answer: `The ordering of a ciphersuite is very important because it decides which algorithms are going to be selected in priority. Each level shows the list of algorithms returned by its ciphersuite. If you have to pick ciphers manually for your application, make sure you keep the ordering.`

For example, your ordering for modern would be very different than what we currently have. See the rationale in each section for more info.
