### ISSUE TITLE
Inconsistent UI selection behavior with Apache-Modern 

### ISSUE THREAD

**Issue by jmanico** [mozilla/server-side-tls#177]
When you first visit [](https://mozilla.github.io/server-side-tls/ssl-config-generator/), Apache and Intermediate are selected, and the Modern selection is disabled.

However, if you then choose Nginx and then choose the choose Modern, you are able to select Apache and get the Apache-Modern selection combination. 

It would be prudent to change this to ensure consistent behavior.

**Comment by jerrykan** [comment]
I've also just noticed this problem. Selecting "Old" then "Modern" also works.

**Comment by szepeviktor** [comment]
@jvehent Are you aware of this bug?

**Comment by jvehent** [comment]
I noticed it, but not sure what's causing this behavior. @gene1wood, any thoughts?

**Comment by szepeviktor** [comment]
Default Apache v2.2.15 does not support "Modern"

**Comment by myrdd** [comment]
The actual issue is that the form is set to the following defaults on page load:

https://github.com/mozilla/server-side-tls/blob/27987097f4fa1815da3f2da6dff25172300c3bd7/ssl-config-generator/index.html#L424-L429

However, when the software (left column) is switched, the ”Server Version“ is always set to the server software's **latest** version:

https://github.com/mozilla/server-side-tls/blob/27987097f4fa1815da3f2da6dff25172300c3bd7/ssl-config-generator/index.html#L481-L483

---

Another issue, which I found when testing what @jerrykan described, is that switching between Old/Intermediate/Modern **will always reset** the Server Version to the latest! The reason: **any** radiobutton changes will pass `change_software = true` to the `renderConfig` function. Switching between Old/Intermediate/Modern is no software change, of course. The code:

https://github.com/mozilla/server-side-tls/blob/27987097f4fa1815da3f2da6dff25172300c3bd7/ssl-config-generator/index.html#L575-L577

BTW, IMHO the position of the Software Version field is not the best one regarding UX. Better would be below or right next to the Server Software (Apache,Nginx,...).

---

Regarding "latest version", see also https://github.com/mozilla/server-side-tls/issues/43

**Comment by april** [comment]
This is all fixed in the new version:
https://mozilla.github.io/ssl-config-generator/
