### ISSUE TITLE
Config generator fails for HAProxy 1.5.4 due to later-introduced 'ssl-default-bind-options' option

### ISSUE THREAD

**Issue by bitsoflogic** [mozilla/server-side-tls#180]
The official news (http://www.haproxy.org/news.html) on October 30th, 2014 states that these global options were added in version HAProxy 1.5.7.  Their documentation doesn't make this obvious.

In my case, I'm using Centos 6.8 with haproxy.x86_64 version 1.5.4-3.el6 installed.  

_Edit: Re-reading it on the news site, I'm not 100% clear if these were added in that patch however they don't seem to be available in the current Centos 6.8 software._

**Comment by floatingatoll** [comment]
Good catch! There's a missing ```if (isSemVer(data.serverVersion, ">=1.5.7")) {``` clause somewhere in the config generator.

**Comment by bitsoflogic** [comment]
http://www.haproxy.org/download/1.5/src/CHANGELOG

2014/04/23 : 1.5-dev23
    - MINOR: config: add global directives to set default SSL ciphers

Maybe it's in that? I'm not sure

**Comment by floatingatoll** [comment]
Noted - we'll have to trace it to a specific commit in a released version. Are you using a vendor's 1.5.4 build or just stock upstream?

**Comment by bitsoflogic** [comment]
What was provided with `yum install`

**Comment by bitsoflogic** [comment]
Looks like the package is found in the CentOS-6 - Base repository: `1.5.4-3.el6` is the latest

**Comment by lukastribus** [comment]
The issue title here is bogus in that "ssl-default-bind-ciphers" works fine, but "ssl-default-bind-options" does not.

While ssl-default-bind-ciphers has been introduced in 1.5-dev23 (haproxy/haproxy-1.5@610f04bbf6b9fa437101f376425e3f27ffef71d3), and therefor works fine in all 1.5 release versions -
 including CentOs' 1.5.4-3.el6, "ssl-default-bind-**options**" has been introduced in 1.5.7 (haproxy/haproxy-1.5@42a3e202504a74c2a6ff7b337726cc42ffa57592).

So yes, "ssl-default-bind-options" and "ssl-default-server-options" need a >=1.5.7 check, falling back to bind line configuration:
`bind    :443 ssl crt /path/to/<cert+privkey+intermediate+dhparam> no-sslv3 no-tls-tickets
`

But, CentOS 6 base repository has now 1.5.18 (1.5.18-1.el6) so this problem is gone at least in CentOs 6.

**Comment by gene1wood** [comment]
It looks like this is less urgent now that Centos 6 has a newer version but if anyone wants to PR this fix feel free to do so.

**Comment by april** [comment]
I believe this has been fixed in the newest version of the generator.
