### ISSUE TITLE
Apply recommendations after The ROBOT Attack

### ISSUE THREAD

**Issue by wojciech-kopras** [mozilla/server-side-tls#203]
Recenty was discovered The ROBOT Attack https://robotattack.org/ . I can see, that the config generator could apply those recommendations, to avoid at all RSA key exchange.

**Comment by lukastribus** [comment]
I disagree.

The modern compatibility set does not include any ciphersuites with the RSA key exchange, so we are already there anyway. The Intermediate and Old backward compatibility set prioritize ECDHE and DHE over RSA key exchanges, but we can't remove RSA because that is exactly the purpose of this set; if we remove RSA key exchange we may as well remove the intermediate and old compatibility set altogether.

This attack is a implementation issue, not a protocol issue; the way to ultimately fix this is to upgrade vulnerable software.

**Comment by wojciech-kopras** [comment]
Maybe you're right. It was only a suggestion based on people from ROBOT attack. 

They said "By disabling RSA encryption we mean all ciphers that start with TLS_RSA". So I thought cipher like "AES128-SHA256" (other name [here](https://www.openssl.org/docs/manmaster/man1/ciphers.html) "TLS_RSA_WITH_AES_128_CBC_SHA256") could be enabled only in "old" profile, not in "intermediate". 

Again, it was only a suggestion based on information from people from ROBOT.

**Comment by Mattia98** [comment]
Shouldn't this be closed then?
