### ISSUE TITLE
support for traefik

### ISSUE THREAD

**Issue by Sohalt** [mozilla/server-side-tls#228]
It would be cool to have support for the traefik.io reverse proxy.

**Comment by captn3m0** [comment]
Looks like this will be helpful for any other projects based on go/crypto because the constant names are quite different: https://godoc.org/crypto/tls#pkg-constants


It is documented at https://github.com/mozilla/server-side-tls/blob/gh-pages/Server_Side_TLS.mediawiki#cipher-names-correspondence-table, but there is no generator on the site that relies on the IANA names right now.

**Comment by april** [comment]
Hey there, you two! There's a brand new generator:

https://github.com/mozilla/ssl-config-generator/
https://mozilla.github.io/ssl-config-generator/

With 100x easier templates. I'd love to have some folks hacking on this.  :)

**Comment by captn3m0** [comment]
@april Thanks!

I've filed an initial PR, but need some help: https://github.com/mozilla/ssl-config-generator/pull/7

**Comment by april** [comment]
This has moved to the other repo, so closing this issue here.
