### ISSUE TITLE
Add support for RHEL8 systemwide update-crypto-policies

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/server-side-tls#245]
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html-single/8.0_release_notes/index#security

Per the RHEL 8.0 release notes from today’s release, they’ve added a systemwide TLS config utility. Please consider updating the generator to support this.

**Comment by tomato42** [comment]
well, either you use Crypto-Policies and accept the guidelines of Red Hat engineers, or you override them and use this guide

as far as I can tell, there is nothing to update...

**Comment by floatingatoll** [comment]
Ah, I see they deferred custom policy support until a later release —

> The individual policy levels (*DEFAULT*, *LEGACY*, *FUTURE*, and *FIPS*)
are included in the *crypto-policies(7)* package. In the future, there will
be also a mechanism for easy creation and deployment of policies defined by
the system administrator or a third party vendor.

You may reject this if you wish, or use it to track that future support,
either WFM.

**Comment by tomato42** [comment]
even when creating custom policies will be supported, the main use case will be slight adjustments (e.g. removal of SHA1 from DEFAULT, adding ARIA to DEFAULT) rather than complete redesign

so yes, I'd say it's not in scope

please re-open or comment on this issue when actual feature set of custom crypto-policies is known and we still want to support them
