### ISSUE TITLE
Sort higher key/hash lenghts to a higher place

### ISSUE THREAD

**Issue by keros** [mozilla/server-side-tls#25]
Currently the apache config looks something like this:

```
SSLHonorCipherOrder     on
SSLCipherSuite          ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:...
```

This makes it more likely that a client use "AES128" instead of "AES256".
Would be nice if the longer key/hash lenghts could be sorted to the first position.

```
SSLHonorCipherOrder     on
SSLCipherSuite          ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:...
```

**Comment by lgarron** [comment]
Right now, the main effect of using AES-256 instead of AES-128 is slower encryption (undesirable for TLS), not better security.

Google Chrome doesn't even implement AES-256-GCM, and [AES-256-CBC is only supported for historical reasons, and might be removed soon](https://code.google.com/p/chromium/issues/detail?id=442572). (Disclaimer: I work on the Chrome security team, so I get to hear folks from the network team rant a lot about security misconceptions.)

As for Mozilla's reason for the ordering, see the [Prioritization Logic section](https://wiki.mozilla.org/Security/Server_Side_TLS#Prioritization_logic) of the wiki page this tool is based on.

**Comment by keros** [comment]
In short:
GCM is much better than CBC (aes128-GCM is better than aes256-CBC)
aes256-GCM has only minimal security advantages over aes128-GCM
aes128-GCM is much faster than aes256-GCM (so aes128-GCM should be prefered)
Thanks for the infos
