### ISSUE TITLE
Add Caddy support

### ISSUE THREAD

**Issue by lhirlimann** [mozilla/server-side-tls#258]

**Comment by floatingatoll** [comment]
@lhirlimann If you can prepare the Caddy config parameter blocks necessary for Intermediate and Modern, that would simplify integrating them into the generator. Looking at Caddy’s current docs, they don’t support any of the Old requirements at all, and they don’t support ciphersuite changes if TLS 1.3 is enabled (as Intermediate and Modern do), and they default-enable TLS 1.3 — so I’m not sure if it’s even possible to configure it to match either Modern or Intermediate, and I’m honestly not sure it’s necessary. (If you’re seeing otherwise in a Caddy deployment, please make sure it’s up-to-date - v1.0.0 - and deployed against a TLS library with TLS 1.3 support and has no tls configuration parameters disabling TLS 1.3.)

https://caddyserver.com/docs/tls

**Comment by april** [comment]
The generator already supports Caddy the best it can given the limitations:

https://ssl-config.mozilla.org/
