### ISSUE TITLE
Current intermediate breaks near-deprecated IE11 on Windows Server 2008R2.

### ISSUE THREAD

**Issue by april** [mozilla/server-side-tls#263]
Apparently there is a very small subset of IE11 users that don't support ECDHE/DHE with RSA, meaning that they have no way to successfully handshake to servers using the current Intermediate configuration.

This includes IE11 on Windows Server 2008R2. The best suites it can negotiate are:

`TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA`
`TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA`

You can see this configuration here:

https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=36

Windows 2008 R2 is at EOL on January 14th, 2020, which makes me somewhat disinclined to update the configuration to support it. But, we have a few options:

• Add the above cipher suites to Intermediate
• Update the note on Intermediate to indicate that you _must_ use an ECDSA certificate to support these systems
• The above, but also add a note to indicate that you can add `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA` if you need to support those very old systems and cannot support anything but RSA for your certificates

**Comment by tomato42** [comment]
adding them to Intermediate would be significant departure so I'd be against that

probably the certificate route should be the recommended one; people that really need compatibility with it (or other obsolete, but still supported systems) can use *Old*

**Comment by naffit** [comment]
Alas.. I'm the one who opened up this can of worms and I've spoken a bit with @april on IRC.

I'm stuck in a situation where the current intermediate suite throws some - albeit soon-to-die - newer browsers out the window, and where the current (v5) old suite is definitely _not_ an option (we are set on deprecating TLSv1 and v1.1).

While January 2020 is soon, I know that we probably wont see the last of these clients before the end of 2020 - the cost of upgrading _now_ is larger than paying Microsoft for extended support for another year (we've seen it before when Windows XP went EOL, so we'll see it again with Windows 7 / Server 2008).

While adding `TLS_RSA_WITH_AES_128_CBC_SHA256` /  `0x3c` / `0x00,0x3c` / `AES128-SHA256` might violate some of the rationales for the current (v5) intermediate suite, I am still stuck between deviating from Mozillas recommendations, showing paying customers the door (and guess what management will say to that..) or using non-billable hours and hours to have 100+ certificates migrated to ECDSA and having to have our customers do a lot of that work too (due to CAA records..).

Apart from not having forward secrecy, why is `TLS_RSA_WITH_AES_128_CBC_SHA256` not listed - ie. what other rationales would be violated?

I think @april's 3rd option about a note would be the best option - then it's a known choice that does not force me to record the reasoning behind us deviating from Mozillas recommendations (and create and maintain our own suite) and still keep the few customers that _will_ take some time to upgrade.

When I first saw the new v5 intermediate suite I also thought of going back to the < v5 modern suite (as can be seen [here](https://wiki.mozilla.org/index.php?title=Security/Server_Side_TLS&oldid=1191414) since it was our startingpoint for TLSv1 and v1.1 deprecation, but the more I thought of that, the more I realised that it would be stuck on that suite with no real way of knowing if, when and who I'd kick away when we would decide to upgrade to later versions.

Over time (the next few years or 4) we should be able to migrate everything from RSA to ECDSA, but I cannot do that within the timeframe we have for dropping TLSv1 and v1.1.

**Comment by tomato42** [comment]
There are plenty of server systems that are still supported that won't work with Intermediate – RHEL 5 for one. But nobody is forcing you to use Mozilla recommendations. Emphasis on _recommendations_.

regarding `TLS_RSA_WITH_AES_128_CBC_SHA256`, the issue is that it's both a non forward secret ciphersuite and it uses cipher block chaining mode (the ones that are hard to implement without being vulnerable to Lucky 13) – I'm not sure why April listed it instead of `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA`... (no, if we are talking about TLS 1.2, the SHA256 is not making it more secure than the SHA1 variant)

> we should be able to migrate everything from RSA to ECDSA,

you don't have to migrate, you can add a second certificate

> it would be stuck on that suite with no real way of knowing if, when and who I'd kick away when we would decide to upgrade to later versions.

the list of clients that the specific settings support is not an exact science; most of the underlying data comes from ssllabs.com

**Comment by april** [comment]
> regarding `TLS_RSA_WITH_AES_128_CBC_SHA256`, the issue is that it's both a non forward secret ciphersuite and it uses cipher block chaining mode (the ones that are hard to implement without being vulnerable to Lucky 13) – I'm not sure why April listed it instead of `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA`... (no, if we are talking about TLS 1.2, the SHA256 is not making it more secure than the SHA1 variant)

I simply missed that it was in the list, no particular technical reason.

I've gone ahead and updated the original comment, as I agree that it's better than `TLS_RSA_WITH_AES_128_CBC_SHA256`.

**Comment by naffit** [comment]
> There are plenty of server systems that are still supported that won't work with Intermediate – RHEL 5 for one. But nobody is forcing you to use Mozilla recommendations. Emphasis on _recommendations_.

Point taken, but we are happy to cut off older browsers (mainly IE) and only support the latest versions of it - and it was just a surprise that what used to be a sure and safe suite all of a sudden broke a lot that we didn't expect. Heck, we have been using various recommendations since around 2013, and I just havn't seen stuff break like this before.

> > we should be able to migrate everything from RSA to ECDSA,
> 
> you don't have to migrate, you can add a second certificate

Alas, adding a second cert is just as requirering as migrating (as well as requering going through an EV process for more than half) - it's really not an option in the short term and for the longer term it would still double the cost and double the time required to handle certs that cannot be moved to Lets Encrypt.

> the list of clients that the specific settings support is not an exact science; most of the underlying data comes from ssllabs.com

Yes, and I'd hate to have to put a complete suite together myself - hence my rather large interest in a suite that is TLSv1.2-only but that allows all current browsers to keep working - even a corner case such as IE11 on an near-EOL version of Windows.

I guess it's a version that lies between Intermediates "Recommended configuration for a general-purpose server" and Olds "Services accessed by very old clients or libraries, such as Internet Explorer 8 (Windows XP), Java 6, or OpenSSL 0.9.8".

**Comment by floatingatoll** [comment]
It seems worth noting here that these are members of a shared versioned
specification, and so while Intermediate 5.0 (I think it is today?) is
unsuitable for your needs, the previous version of Modern or Intermediate
might well meet your needs until you’re able to deprecate those clients. If
you’re already aware and this isn’t of any help, my apologies - I just
wanted to be sure it was considered.

**Comment by april** [comment]
> Point taken, but we are happy to cut off older browsers (mainly IE) and only support the latest versions of it - and it was just a surprise that what used to be a sure and safe suite all of a sudden broke a lot that we didn't expect. Heck, we have been using various recommendations since around 2013, and I just havn't seen stuff break like this before.

As far as I know, the 5.0 guidelines have been widely used, and this is the only known compatibility problem with them: a browser running on a near-EOL version of Windows Server that didn't receive cipher suite updates like the rest of Windows installations did. And even then, there are only issues when the server is unable to switch to (or add) an ECDSA certificate, as the guidelines recommend.

This is why we have the _Old_ configuration, to push your browser support from 99.999%-ish to something even higher. This doesn't affect IE11 installations that you are likely to see, only those who are choosing to live dangerously by having people browse from Citrix installations using Windows Server versions that will cease receiving security updates in three months.

**Comment by bmw** [comment]
Please let me know if there's a better place I should ask questions about this, but do we know if this also affects IE 11 on Windows 7 (as suggested by [SSLLabs](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=36))?

I'm trying to decide if it makes sense for Certbot to allow `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA` when configuring the servers it runs on as we follow the intermediate recommendations and can't switch people over to ECDSA certificates just yet.

**Comment by april** [comment]
If there is a Windows 7 configuration it does affect, nobody has reported it to me yet. Given that Windows 7 + IE11 is still a decent chunk of the browser market, I'm sure I would have heard about it plenty by now.

All but that singular entry for Windows 7 + IE 11 work, and that key (36) is much earlier than all the other Windows 7 entries. So I'm pretty sure it's just Windows 2008 R2.

That said, it's not terribly harmful to add it in cases where you can't use ECDSA certificates. Given that Certbot supports a ton of systems of unknown origins, I would probably recommend it for RSA-only configurations.

**Comment by bmw** [comment]
Thanks for the additional information!

We made the change to allow this cipher suite in our release today.

**Comment by polarathene** [comment]
> Apparently there is a very small subset of IE11 users that don't support ECDHE/DHE with RSA

While this has already been resolved, just for clarification, the quoted statement meant to further constrain the issue towards AEAD cipher compatibility? Since the solution of offering ECDHE/DHE + RSA + CBC would make little sense otherwise.

~That conflicts with the earlier in the year statement [here](https://github.com/mozilla/server-side-tls/issues/244#issuecomment-490125353) (May 2019):~

> IE 11 on Win 7/8 supports ECDHE+ECDSA or DHE+RSA for AES-GCM but not ECDHE+RSA.

---

**EDIT:**

> All but that singular entry for Windows 7 + IE 11 work, and that key (36) is much earlier than all the other Windows 7 entries. So I'm pretty sure it's just Windows 2008 R2.

Originally I didn't quite get what was being stated here (with the mention of key number), I see that referred to Qualys user agent URL, and have resolved what appeared to be conflicting information at a glance. Sharing below for anyone else it may benefit in future:

The source of a Qualys user agent client link [isn't the only result for IE11 + Windows 7](https://www.ssllabs.com/ssltest/clients.html), where all the others listed [are able to provide DHE + RSA + AES-GCM](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=143). 

- Initial release of [IE11 (Oct 2013)](https://en.wikipedia.org/wiki/Internet_Explorer_11) seems to have been the [first listed user agent (key 36)](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=36)
- The first update for IE11 ([Possibly Nov 2013](https://msrc-blog.microsoft.com/2013/11/12/security-advisory-2868725-recommendation-to-disable-rc4/)) arrived to create the next [user agent update (key 95)](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=95), DHE + RSA + AES-GCM support became available. ECDHE + RSA was also given priority over RSA key exchange, but not ECDHE + ECDSA.
-  The next update update [dropped SSLv3 (key 102)](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=102), presumably due to POODLE (Oct 2014) - Seems to be [April 2015](https://docs.microsoft.com/en-us/archive/blogs/ie/april-2015-security-updates-for-internet-explorer)
- Then we have [user agent update (key 133)](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=133) appears to be from [June 2016](https://support.microsoft.com/en-nz/help/3161639), it adds two new ciphers DHE + RSA + CBC + SHA.
- Finally with [the last IE11 user agent (key 143)](https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=143), it appears to be tied to an update in [August 2016](https://support.microsoft.com/en-nz/help/3151631/rc4-cipher-is-no-longer-supported-in-internet-explorer-11-or-microsoft) which describes removal for RC4 and links to [MS16-095](https://support.microsoft.com/en-nz/help/3175443/ms16-095-security-update-for-internet-explorer-august-9-2016) (see the "More Information" section). This is the only update that dropped support for RC4 cipher suites from all the user agents. Interestingly though, *key 143* cipher suites listed show the previously added DHE + RSA + CBC + SHA additions were removed.
