### ISSUE TITLE
Relationship between this repo's json standard and ssl-config-generator's json standard

### ISSUE THREAD

**Issue by gene1wood** [mozilla/server-side-tls#287]
In 2019 when #255 was merged the [`server-side-tls-conf-5.0.json`](https://github.com/mozilla/server-side-tls/blob/gh-pages/json/server-side-tls-conf-5.0.json) file in this repo was nearly the same as the [`5.0.json`](https://github.com/mozilla/ssl-config-generator/blob/master/docs/guidelines/5.0.json) file in the [ssl-config-generator](https://github.com/mozilla/ssl-config-generator) repo.

Subsequent to that, new versions of the standard were published in https://github.com/mozilla/ssl-config-generator but not here

* Is that an oversite and these json files should exist in both repos, matchin each other?
* Is there a reason that the newest version here is 5.0 and in ssl-config-generator it's 5.6?

I can fix things up, just wanted to figure out the reason for the difference.
@april Do you have any recollection on this?

**Comment by april** [comment]
I believe I had decided that it made sense to have the JSON files in the SSL config repository instead of here, as it consumed them to generate the configs.

Otherwise they would need to be in both places, or make a CORS request, both of which were not great.

5.0 was left here so as to not break any existing links on the internet.

**Comment by gene1wood** [comment]
Perfect, that's exactly what I needed to know, thank you. I'll add to the READMEs to clarify this.

**Comment by gene1wood** [comment]
Fixed in #288
