### ISSUE TITLE
cipherspec can be made less verbose

### ISSUE THREAD

**Issue by montesse** [mozilla/server-side-tls#5]
The cipherspecs generated are very long. Thanks to the format needed, that also makes them really hard to read.  You can generate the lists with much more concise (and readable) cipherspecs.  For examples, the settings of "modern" and "intermediate" settings with openssl v1.0.1 are:

Modern: AES+kEECDH:AES+kEDH:!aNULL:@STRENGTH
Intermediate: HIGH:-kECDH:-3DES:DES-CBC3-SHA:!PSK:!MD5:!aNULL:@STRENGTH

The modern spec adds in two DHE-RSA-AES-SHA ciphers I believe you omitted by accident.  I find it odd there would be only one allowed 3DES cipher for the intermediate spec--I would love to hear why.  I'm also curious why you don't allow ECDH ciphers?

I hope this helps. The generator is really nifty and it would be great if it was smarter about the cipherspecs!

**Comment by gertvdijk** [comment]
The ciphers are coming from [Mozilla Wiki: Security/Server Side TLS](https://wiki.mozilla.org/Security/Server_Side_TLS). I don't see how your Modern/Intermediate ciphersuite configuration string would be comparable to those. You can verify yourself using

```
openssl ciphers -v '<ciphersuite string>'
```

The `@STRENGTH` ordering doesn't really do the same as described in the wiki article as OpenSSL then orders in a very naive way (by encryption key size). E.g. `DHE-RSA-AES256-SHA` isn't preferable over `ECDHE-RSA-AES128-GCM-SHA256`, in practice.

**Comment by jvehent** [comment]
As @gertvdijk mentioned, you need a very long ciphersuite in order to sort the ciphers correctly. There is just no way, in OpenSSL, to obtain an exact ordering of ciphers with a shorter ciphersuite. And the ordering of ciphers is paramount to our guidelines.

I understand that it's long and some could thing of it as ugly. But if you look at it as a perfectly ordered ciphersuite, you'll start seeing the beauty in it ;)

**Comment by jvehent** [comment]
I forgot to answer some of your questions. Although I think the talk section of the guidelines would be a better place for this discussion, this repository is really for the tool itself and not the guidelines.

> The modern spec adds in two DHE-RSA-AES-SHA ciphers I believe you omitted by accident.

I don't see any duplicate in the current ciphersuite. Did I miss something?

```
DHE-RSA-AES128-SHA256
DHE-RSA-AES128-SHA
DHE-DSS-AES128-SHA256
DHE-RSA-AES256-SHA256
DHE-DSS-AES256-SHA
DHE-RSA-AES256-SHA
```

> I find it odd there would be only one allowed 3DES cipher for the intermediate spec--I would love to hear why.

`DES-CBC3-SHA` is needed for compatibility with older clients. but since that is the only one needed for backward compatibility, the others are discarded

> I'm also curious why you don't allow ECDH ciphers?

ECDH ciphers require special certificates that are not used, and thus the ciphers are disabled.
